# Generated by Django 4.0.4 on 2022-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_settlement',
            field=models.DateField(db_index=True, default='2022-01-01', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='time_of_settlement',
            field=models.TimeField(db_index=True, default='00:00:00', verbose_name='Time'),
        ),
    ]
