# Generated by Django 4.0.4 on 2022-06-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_change1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name'], 'verbose_name': 'Відвувач', 'verbose_name_plural': 'Відвідувачі'},
        ),
    ]
