# Generated by Django 4.0.4 on 2022-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_settlement_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='room_type',
            field=models.CharField(choices=[('LUX', 'Luxury Room'), ('FAM', 'Family Room'), ('SINGLE', 'single Room'), ('DOUBLE', 'Double Room')], max_length=30, verbose_name='Room Type'),
        ),
    ]
