# Generated by Django 4.0.4 on 2022-06-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_customer_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.customer', verbose_name='Customer'),
        ),
    ]
