# Generated by Django 4.0.4 on 2022-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_settlement_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
